"""Prepare strict method-only metadata, zero client/runtime resource changes; no tests/build/GPU/git/network."""
import ast,copy,hashlib,json,subprocess
from pathlib import Path
w=Path('/workspace/neon-candidates/harbor-ferry-long-corridor-verification-final-20261005');r=Path('/workspace/neon-candidates/harbor-ferry-long-corridor-verification-final-20261005-review');q=w/'docs/qa/ferry-long-corridor-adoption-20261005';b=w/'tools/native-review';a=b/'runtime-amendments/ferry-source-axis-long-centre-hall-20261005'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def load(p):return json.loads(p.read_text())
def save(p,v):assert not p.exists(),p;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
def cp(p,t):assert not t.exists(),t;t.parent.mkdir(parents=True,exist_ok=True);t.write_bytes(p.read_bytes())
old=load(r/'original-native208-bundle-manifest-986.json');original=load(r/'original-committed-986208-build-info.json');source=load(r/'original-all401-source-hashes-986.json');adopt=load(r/'literal-payload-adoption-receipt.json');payload=adopt['actualAdoptedPayloadFiles'];allow={str(Path(p).relative_to('tools/native-review')) for p in payload}|{'README.md'}
assert len(original['assets'])==208 and len(source)==401 and {p:sha(w/p) for p in source}==source
for p,pin in original['assets'].items():assert sha(w/p)==sha(w/'dist'/p)==pin,p
for p,row in old['files'].items():
 if p not in allow:assert sha(b/p)==row['sha256'],p
cp(r/'original-native208-bundle-manifest-986.json',a/'original-native208-bundle-manifest-986.json');cp(r/'original-transport-method-manifest-986.json',a/'original-transport-method-manifest-986.json');cp(r/'literal-payload-adoption-receipt.json',a/'actual-literal-adoption-receipt.json')
bridge={'status':'EXACT208_GRAPHICS_ONLY_AND401_GAMEPLAY_SOURCE_IDENTITY_BRIDGE','parentCommit':'986db512e6268ea5228da4fd360db4317134dd2e','parentCommittedRaw208BuildInfoSHA256':sha(r/'original-committed-986208-build-info.json'),'actualEntire208RuntimeAssets':original['assets'],'sourceManifestSHA256':sha(r/'original-all401-source-hashes-986.json'),'productionTestSourceCount':401,'all401SourceBytesExact986':True,'all208ResourceBytesActualSourceAndMaterializedDistExact986':True,'runtimeSourceDelta':{'changed':[],'added':[],'removed':[],'unchangedCount':208},'graphicsShaderGeometryMapLightingCameraPhysicsQualityAndClientInputsUnchanged':True,'baseline156AndRuntimeExpectedDictionaryAndBPhysicalGeometrySourceProofUnchanged':True,'nativeProtocolLiteralPayloadFiles':payload,'clientFull381InputsUnchangedNoLocalRerun':True,'newNativeFerryOutcomePending':True,'newNativePassInherited':False,'adopterActualGpuPixelReviewExecuted':False,'scope':'Exact identity permits source-scoped use of original986 graphics evidence only. Each original image/art decision retains its own actual capture and review outcome; this bridge does not fabricate an acceptance. Ferry validation protocol is explicitly changed, its new native run remains required. Revision-only build after ROOT commit is checked separately.'};save(a/'exact208-graphics-and401-source-bridge.json',bridge)
p=b/'README.md';p.write_text(p.read_text()+'\nCurrent Ferry-only protocol is source-identical986:208 runtime resources/401 production-test files unchanged; exact graphics-only bridge retains original986 capture decisions and does not sign any new native PASS. Explicitce3 method/6dce manifest/3682 amendment add300s only to >=12m nonprecision centre-hall Ferry legs; otherlocal150/whole2400/berth1200/case110 budgets remain. Original first failure1b2b and source stress negatives are unchanged. Native-only tools revision requires new actual Ferry execution; no localclient381/build/GPU was rerun here.\n')
files={str(p.relative_to(b)):{'sha256':sha(p),'bytes':p.stat().st_size} for p in sorted(b.rglob('*')) if p.is_file() and p!=b/'bundle-manifest.json'}
receipt={'status':'ACTUAL_NATIVE_ONLY_FERRY_METADATA_PREPARED_NO_RUNTIME_CHANGE','parentCommit':'986db512e6268ea5228da4fd360db4317134dd2e','originalNative208ManifestSHA256':sha(r/'original-native208-bundle-manifest-986.json'),'parentCommitted208RawSHA256':sha(r/'original-committed-986208-build-info.json'),'actual208RuntimeAssets':original['assets'],'source401ManifestSHA256':sha(r/'original-all401-source-hashes-986.json'),'explicitPayloadFiles':payload,'actualExpectedNativeFileCount':len(files),'actualExpectedNativeFiles':files,'graphicsOnlyBridgePath':'runtime-amendments/ferry-source-axis-long-centre-hall-20261005/exact208-graphics-and401-source-bridge.json','graphicsOnlyBridgeSHA256':sha(a/'exact208-graphics-and401-source-bridge.json'),'nativePass':False};save(r/'metadata-refresh-receipt.json',receipt)
src=Path('/workspace/neon-candidates/harbor-mineral-pattern-correction-final-20261005-review/strict-one-west-pattern-source-pin-sealer.py');assert sha(src)=='f3470bdcd0cd6376e4e1bf3a4336ac71d43dd1dbcc20b44253be0e0666090800';script=src.read_text();start=script.index(' # Strict actual single-West bridge;');end=script.index(" problem(build['assets']==authored['assets']",start)
guard=f''' # Strict exact runtime identity; only three reviewed native method payloads may differ.
 final_receipt_path=Path({str(r/'metadata-refresh-receipt.json')!r});problem(digest(final_receipt_path)=={sha(r/'metadata-refresh-receipt.json')!r},'Native-only actual receipt changed');final_receipt=load(final_receipt_path)
 problem(final_receipt['status']=='ACTUAL_NATIVE_ONLY_FERRY_METADATA_PREPARED_NO_RUNTIME_CHANGE','Native-only actual scope missing')
 problem(build['assets']==final_receipt['actual208RuntimeAssets'] and len(build['assets'])==208,'Entire208 graphics dictionary changed')
 for rel,pin in final_receipt['actual208RuntimeAssets'].items():
  problem(digest(contained(w,rel))==digest(contained(w/'dist',rel))==pin,'Native-only resource/source differs from986:'+rel)
 source_path=Path({str(r/'original-all401-source-hashes-986.json')!r});problem(digest(source_path)==final_receipt['source401ManifestSHA256'],'Original source401 manifest changed')
 source=load(source_path);problem(len(source)==401 and all(digest(contained(w,p))==pin for p,pin in source.items()),'Native-only production/test source differs from986')
 original_catalog=load(b/'runtime-amendments/ferry-source-axis-long-centre-hall-20261005/original-native208-bundle-manifest-986.json');problem(digest(b/'runtime-amendments/ferry-source-axis-long-centre-hall-20261005/original-native208-bundle-manifest-986.json')==final_receipt['originalNative208ManifestSHA256'],'Original native208 history changed')
 protocol_paths={{str(Path(p).relative_to('tools/native-review')) for p in final_receipt['explicitPayloadFiles']}}
 for rel,row in original_catalog['files'].items():
  if rel not in protocol_paths|{{'README.md'}}:problem(digest(contained(b,rel))==row['sha256'],'Unapproved old native208 method/input/proof/seal/case/budget changed:'+rel)
 for rel,row in final_receipt['explicitPayloadFiles'].items():problem(digest(contained(w,rel))==row['sha256'] and contained(w,rel).stat().st_size==row['bytes'],'Explicit Ferry nativepayload differs:'+rel)
 actual_native={{str(p.relative_to(b)):{{'sha256':digest(p),'bytes':p.stat().st_size}} for p in b.rglob('*') if p.is_file() and p!=b/'bundle-manifest.json'}}
 problem(actual_native==final_receipt['actualExpectedNativeFiles'] and len(actual_native)==final_receipt['actualExpectedNativeFileCount']=={len(files)},'Complete native-only inventory changed')
 problem(not any(p.is_symlink() or '__pycache__' in p.parts or p.suffix=='.pyc' for p in b.rglob('*')),'Nativebundle cannot admit cache/symlink')
 notes.append('Exact208 graphics-only resource identity and401 gameplay/test source identity to986; only literal reviewed Ferry nativeprotocol changed. Original image/outcome scope preserved; no new native pass.')
'''
script=script[:start]+guard+script[end:]
line=next(x for x in script.splitlines() if x.startswith(" catalog['mineralPatternCorrectionRuntimeAmendment']="));script=script.replace(line," problem(catalog['mineralPatternCorrectionRuntimeAmendment']==original_catalog['mineralPatternCorrectionRuntimeAmendment'],'Original986 graphics/source amendment changed')")
insert=" catalog['ferrySourceAxisAndFiniteLongHallNativeMethodAmendment']={'status':'EXPLICIT_NATIVE_METHOD_ONLY_CPU_SOURCE_PROOF_NATIVE_PENDING','parentNativeBundleFileCount':208,'parentNativeBundleManifestSHA256':final_receipt['originalNative208ManifestSHA256'],'actualNativeBundleFileCount':final_receipt['actualExpectedNativeFileCount'],'actual208GraphicsOnlyBridgePath':final_receipt['graphicsOnlyBridgePath'],'actual208GraphicsOnlyBridgeSHA256':final_receipt['graphicsOnlyBridgeSHA256'],'explicitPayloadFiles':final_receipt['explicitPayloadFiles'],'all208RuntimeAnd401GameplaySourcesUnchanged':True,'oldFailuresPreserved':True,'nativePass':False}\n"
script=script.replace(" catalog['activityPinRefresh']=",insert+" catalog['activityPinRefresh']=",1);ast.parse(script);dst=r/'strict-native-only-ferry-source-pin-sealer.py';assert not dst.exists();dst.write_text(script);save(r/'strict-sealer-derivation-receipt.json',{'status':'NATIVE_ONLY_STRICT_COPY_FROM_IMMUTABLE_PATTERN_F347','originalSealerSHA256':sha(src),'newSealerSHA256':sha(dst),'nativeFileCount':len(files),'sourceRuntimeDeltaZero':True,'originalGuardCompletelyReplaced':True,'testsBuildGpuOrNetworkExecuted':False});print(json.dumps({'status':'PREPARED','nativeFiles':len(files),'receiptSHA256':sha(r/'metadata-refresh-receipt.json'),'strictSealerSHA256':sha(dst)}))
