"""ROOT-only one revision build after exact reviewed native-only commit; no rule/native execution."""
import argparse,datetime,hashlib,json,os,re,subprocess,time
from pathlib import Path
ROOT=Path('/workspace/neon-candidates/harbor-ferry-long-corridor-verification-final-20261005');REVIEW=Path('/workspace/neon-candidates/harbor-ferry-long-corridor-verification-final-20261005-review');PARENT='986db512e6268ea5228da4fd360db4317134dd2e'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def load(p):return json.loads(p.read_text())
def git(*a):return subprocess.check_output(['git',*a],cwd=ROOT,text=True).strip()
def save(out,name,v):p=out/name;assert not p.exists();p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
def native():
 b=ROOT/'tools/native-review';assert not any(p.is_symlink() or '__pycache__' in p.parts or p.suffix=='.pyc' for p in b.rglob('*'));return {str(p.relative_to(b)):{'bytes':p.stat().st_size,'sha256':sha(p)} for p in sorted(b.rglob('*')) if p.is_file() and p!=b/'bundle-manifest.json'}
def main():
 ap=argparse.ArgumentParser();ap.add_argument('--head',required=True);ap.add_argument('--tree',required=True);ap.add_argument('--stage-ledger',required=True);ap.add_argument('--stage-ledger-sha256',required=True);ap.add_argument('--output',required=True);a=ap.parse_args();assert all(re.fullmatch('[0-9a-f]{40}',x) for x in [a.head,a.tree]);assert git('rev-parse','HEAD')==a.head and git('rev-parse','HEAD^{tree}')==a.tree and git('rev-list','--parents','-n','1',a.head).split()==[a.head,PARENT];assert not subprocess.check_output(['git','status','--porcelain','--untracked-files=no'],cwd=ROOT)
 lp=Path(a.stage_ledger);assert sha(lp)==a.stage_ledger_sha256;l=load(lp);assert l['status']=='ACTUAL_NATIVE_ONLY_FERRY_SOURCE_METADATA_STAGE_READY_NATIVE_PENDING' and l['parentCommit']==PARENT and l['actualSourceFileCount']==401 and l['actualResourceCount']==208;assert set(git('diff','--name-only',PARENT,a.head).splitlines())==set(l['files'])
 for p,row in l['files'].items():assert sha(ROOT/p)==row['sha256'] and (ROOT/p).stat().st_size==row['bytes']
 reference=REVIEW/'original-committed-986208-build-info.json';assert sha(reference)=='2c6d318d93909e786406c1c1b1ca8aea3d64f84d9fbe832c53219510ba91a3a7';expected=load(reference);assert expected['revision']==PARENT and len(expected['assets'])==208;source=load(REVIEW/'original-all401-source-hashes-986.json');assert len(source)==401 and {p:sha(ROOT/p) for p in source}==source
 assert load(ROOT/'tools/native-review/expected-runtime-dictionaries.json')==load(REVIEW/'original-expected-runtime-dictionaries-986.json');assert sha(ROOT/'tools/native-review/methods/transport/native-transport-high.mjs')=='ce3fed236f6f91f9d7bb56479ee961bce19bdee89544efe39d67b6fe01b2ea2f'
 catalog=ROOT/'tools/native-review/bundle-manifest.json';nb=native();assert load(catalog)['files']==nb and len(nb)==l['actualNativeBundleFileCount'] and sha(catalog)==l['actualNativeBundleManifestSHA256'];assert all(sha(ROOT/p)==pin for p,pin in expected['assets'].items())
 paths=[p for p in subprocess.check_output(['git','ls-files','-z'],cwd=ROOT).decode().split('\0') if p];status=subprocess.check_output(['git','status','--porcelain','-z'],cwd=ROOT);before={p:sha(ROOT/p) for p in paths};out=Path(a.output).resolve();assert not out.exists() and not out.is_relative_to(ROOT);out.mkdir(parents=True);save(out,'all-tracked-hashes-before.json',before);save(out,'all401-source-hashes-before.json',source);save(out,'native-inventory-before.json',nb)
 env=os.environ.copy();env['GITHUB_SHA']=a.head;started=datetime.datetime.now(datetime.timezone.utc).isoformat();t=time.monotonic()
 with (out/'build.stdout.log').open('wb') as stdout,(out/'build.stderr.log').open('wb') as stderr:run=subprocess.run(['npm','run','build'],cwd=ROOT,env=env,stdout=stdout,stderr=stderr)
 raw=(ROOT/'dist/build-info.json').read_bytes();(out/'committed-build-info-original.json').write_bytes(raw);actual=json.loads(raw);after={p:sha(ROOT/p) for p in paths};after_source={p:sha(ROOT/p) for p in source};after_native=native();save(out,'all-tracked-hashes-after.json',after);save(out,'all401-source-hashes-after.json',after_source);save(out,'native-inventory-after.json',after_native)
 checks={'buildExitZero':run.returncode==0,'allTrackedFrozen':before==after,'all401SourceExact986BeforeAfter':source==after_source,'allNativeInventoryFrozen':nb==after_native and sha(catalog)==l['actualNativeBundleManifestSHA256'],'gitHeadTreeStatusFrozen':git('rev-parse','HEAD')==a.head and git('rev-parse','HEAD^{tree}')==a.tree and status==subprocess.check_output(['git','status','--porcelain','-z'],cwd=ROOT),'actualRevisionNewHEAD':actual.get('revision')==a.head,'version08Preserved':actual.get('version')=='0.8.0','all208GraphicsResourcesLiteral986':actual['assets']==expected['assets'] and len(actual['assets'])==208,'all208ActualSourceAndDistExact':all(sha(ROOT/p)==sha(ROOT/'dist'/p)==pin for p,pin in actual['assets'].items())}
 receipt={'status':'ACTUAL_COMMITTED_NATIVE_ONLY_FERRY_BUILD_PASS_NATIVE_PENDING' if all(checks.values()) else 'ACTUAL_COMMITTED_NATIVE_ONLY_FERRY_BUILD_FAILED_OUTPUTS_PRESERVED','commit':a.head,'tree':a.tree,'parent':PARENT,'assets':len(actual['assets']),'actualBuildSHA256':sha(out/'committed-build-info-original.json'),'trackedFiles':len(paths),'sourceFiles':len(source),'nativeBundleFiles':len(nb),'nativeBundleManifestSHA256':sha(catalog),'stageLedgerPath':str(lp),'stageLedgerSHA256':sha(lp),'checks':checks,'original986381InputsUnchangedNoLocalRerun':True,'testsRerun':False,'buildExit':run.returncode,'startedAtUTC':started,'elapsedSeconds':time.monotonic()-t,'stdoutSHA256':sha(out/'build.stdout.log'),'stderrSHA256':sha(out/'build.stderr.log'),'nativeGpuOrNetworkExecuted':False,'newNativePass':False};save(out,'receipt.json',receipt);print(json.dumps(receipt));return 0 if all(checks.values()) else 1
if __name__=='__main__':raise SystemExit(main())
