import json,hashlib,math,subprocess
from pathlib import Path
D=Path('/workspace/neon-candidates/ferry-fresh-relative-public-aim-candidate-20261005');P=Path('/workspace/neon-candidates/harbor-combined-transit-art-final-20261005')
h=lambda b:hashlib.sha256(b).hexdigest();ref=lambda p:{'path':str(p),'bytes':p.stat().st_size,'sha256':h(p.read_bytes())}
old=(D/'original-15c-active-2e9-native-transport-high.mjs').read_bytes();new=(D/'payload/tools/native-review/methods/transport/native-transport-high.mjs').read_bytes();rev=json.loads((D/'EXACT_SOURCE_REVERSAL.json').read_text());assert h(old)==rev['parentMethodSHA256'];assert h(new)==rev['candidateMethodSHA256'];s=new.decode()
for c in reversed(rev['changes']):s=s.replace(c['new'],c['old'])
assert s.encode()==old
cpu=json.loads((D/'ACTUAL_SOURCE_FERRY_RELATIVE_AIM_CPU_RECEIPT.json').read_text());n6=next(r for r in cpu['rows'] if 'n6-start' in r['name']);frames=[]
for p in n6['leg']['aimPhases']:
 for q in p['progress']:
  if q['when'] not in ['fresh-relative-before-public-input','fresh-relative-readonly-waiter']:continue
  desired=q.get('desired');yaw=q['observed']['camera']['yaw'];frames.append({'when':q['when'],'status':q['status'],'syntheticWallTimestamp':q['at'],'simulationTime':q['observed']['simulationTime'],'actualSourceVehicleYaw':q['observed']['vehicle']['yaw'],'actualSourceCameraYaw':yaw,'actualSourceRelativeDesiredYaw':desired,'angleGap':abs(math.atan2(math.sin(yaw-desired),math.cos(yaw-desired)))})
proof={'status':'BLOCKED_KNOWN_SOURCE_TIME_AND_CAMERA_LAG_PRESSURE_DO_NOT_DISPATCH_AS_NATIVE_READY','candidateCodeUnchangedAfterInitialGeneration':True,'candidateMethod':ref(D/'payload/tools/native-review/methods/transport/native-transport-high.mjs'),'parentMethod':ref(D/'original-15c-active-2e9-native-transport-high.mjs'),'sourceHEAD':subprocess.check_output(['git','-C',str(P),'rev-parse','HEAD'],text=True).strip(),'actualSourceRawBuild':ref(P/'dist/build-info.json'),'cpuReceipt':ref(D/'ACTUAL_SOURCE_FERRY_RELATIVE_AIM_CPU_RECEIPT.json'),'literalBusTramCPUReceipt':ref(D/'BUS_TRAM_LITERAL_PUBLIC_ACTION_AND_MOTION_CPU_RECEIPT.json'),'exactReversal':ref(D/'EXACT_SOURCE_REVERSAL.json'),'firstOriginalFailureReviewSeal':ref(Path('/workspace/neon-candidates/current220-ferry-high-first-failure-original-deep-readonly-review-20261005/SEAL.json')),'sourcePhysicalMath':{'cameraFormula':'cameraNext = cameraPrevious + angle(requestedOrbitYaw-cameraPrevious)*(1-exp(-12*actualFrameDt))','dt':.25,'weight':1-math.exp(-3),'passengerUpdate':'15 actual source 1/60 substeps; input camera sampled before steps; real boat source updates before stepPlayer; camera update after steps','newProtocolPressureSeed':'Original authored lower5 n6 aim before-input snapshot sim109.4333333333284, local[-2.3172491509258943,1.3,-7.221266538349477], camera3.19833879580247','fixtureCaveat':'7666.4ms per frame is a fixed pressure fixture from an observed original High-frame value; not whole-run mean and not a native result. It represents a relevant potential slow frame condition, not an environment exemption.','failure':'8 real public mouse corrections, 8 physical frames, no movement key, original60 aim deadline reached because fixed current orbit requested before frame lags the newly rotated Ferry relative target by .084-.110 radians, above original.025. Only initial one full and one compact read; remaining observations are small handles.','correctedCausalScope':'Some old desired goals equal the relative goal at the aim before-input read. The observed source gap can arise between camera-match and later guard/physical frame; do not claim every outer state was already stale before aim.','rawNativeKeyWallTimestampsAvailable':False},'pressureRows':frames,'necessaryNextConsideration':'Finite real public-mouse anticipation from actually observed boat yaw change and actual unchanged ChaseCamera damping, with every successful control frame still independently matching actual current goal at original.025. No future simulation/camera/world setter and no budget/tolerance weakening. Not implemented or approved here.','limits':{'genericAimAndPhotoAndHeldObserverLiteral':True,'sourceRuntimeChanged':False,'nativeExecuted':False,'GPUExecuted':False,'nativePassed':False,'finalReleasedDiagnosticRPCRejectionSeparatelyInjected':False,'errorAndCleanupSourceBlocksLiteral':True,'originalHarnnessAssumptionFailuresPreserved':True}}
(D/'KNOWN_SOURCE_PRESSURE_BLOCKER_AND_TEMPORAL_FINDINGS.json').write_text(json.dumps(proof,indent=2)+'\n')
inputpins={p:ref(P/p)for p in ['src/main.js','src/harbor-transit.js','src/camera.js','src/city-exploration.js','src/harbor-vehicle-models.js','tools/native-review/methods/transport/native-transport-high.mjs','tools/native-review/methods/transport/method-manifest.json','tools/native-review/methods/transport/canonical-layouts.json','tools/native-review/methods/transport/runtime-resources.json','dist/build-info.json']}
(D/'READONLY_INPUT_LEDGER.json').write_text(json.dumps({'sourceHead':proof['sourceHEAD'],'sourcePins':inputpins,'sourceWrites':False,'nativeExecuted':False},indent=2)+'\n')
(D/'preparer-original.py').write_bytes(Path('/workspace/neon-candidates/prepare-ferry-fresh-relative-aim-candidate-20261005.py').read_bytes())
(D/'sealer-original.py').write_bytes(Path(__file__).read_bytes())
files=[]
for p in sorted(D.rglob('*')):
 assert not p.is_symlink()
 if p.is_file():files.append({'path':str(p.relative_to(D)),'bytes':p.stat().st_size,'sha256':h(p.read_bytes())})
seal={'status':'CLOSED_BLOCKED_PROTOCOL_PRESSURE_CANDIDATE_NOT_NATIVE_READY','inventory':files,'fileCount':len(files),'SHA256Algorithm':'sha256','nativePass':False,'originalFailedRunsPreserved':True}
(D/'SEAL.json').write_text(json.dumps(seal,indent=2)+'\n')
print(json.dumps({'directory':str(D),'seal':ref(D/'SEAL.json'),'blocker':ref(D/'KNOWN_SOURCE_PRESSURE_BLOCKER_AND_TEMPORAL_FINDINGS.json'),'fileCount':len(files)}))
