"""ROOT-only committed revision build, guarded by the actual final null-build and exact reviewed stage ledger. Never tests/GPU/network."""
import argparse,datetime,hashlib,json,os,re,subprocess,time
from pathlib import Path
W=Path('/workspace/neon-candidates/harbor-combined-transit-art-final-20261005');PARENT='220312885a7b1a7a987790aa4f9d1d38b294be90'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def load(p):return json.loads(p.read_text())
def save(o,n,v):p=o/n;assert not p.exists();p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
def git(*a):return subprocess.check_output(['git',*a],cwd=W,text=True).strip()
def native():
 b=W/'tools/native-review';assert not any(p.is_symlink() or '__pycache__' in p.parts or p.suffix=='.pyc' for p in b.rglob('*'));return {str(p.relative_to(b)):{'sha256':sha(p),'bytes':p.stat().st_size} for p in sorted(b.rglob('*')) if p.is_file() and p!=b/'bundle-manifest.json'}
def main():
 ap=argparse.ArgumentParser();ap.add_argument('--head',required=True);ap.add_argument('--tree',required=True);ap.add_argument('--stage-ledger',required=True);ap.add_argument('--stage-ledger-sha256',required=True);ap.add_argument('--output',required=True);a=ap.parse_args()
 assert all(re.fullmatch('[0-9a-f]{40}',v) for v in [a.head,a.tree]);assert git('rev-parse','HEAD')==a.head and git('rev-parse','HEAD^{tree}')==a.tree and git('rev-list','--parents','-n','1',a.head).split()==[a.head,PARENT];assert not subprocess.check_output(['git','status','--porcelain','--untracked-files=no'],cwd=W)
 lp=Path(a.stage_ledger);assert sha(lp)==a.stage_ledger_sha256;l=load(lp);assert l['status']=='ACTUAL_COMBINED_REFERENCE_SOURCE_METADATA_STAGE_READY_NATIVE_AND_ART_PENDING' and l['parentCommit']==PARENT
 assert set(git('diff','--name-only',PARENT,a.head).splitlines())==set(l['files'])
 for p,row in l['files'].items():assert sha(W/p)==row['sha256'] and (W/p).stat().st_size==row['bytes'],p
 np=Path(l['actualNullBuildInfoPath']);assert sha(np)==l['actualNullBuildInfoSHA256'];expected=load(np);assert expected['revision'] is None and expected['version']=='0.8.0' and len(expected['assets'])==l['actualResourceCount']
 sp=Path(l['actualSourceManifestPath']);assert sha(sp)==l['actualSourceManifestSHA256'];source=load(sp);assert len(source)==l['actualSourceFileCount'] and all(sha(W/p)==v for p,v in source.items())
 dicts=load(W/'tools/native-review/expected-runtime-dictionaries.json');assert dicts['authored']['assets']==expected['assets'] and len(dicts['baseline']['assets'])==156;assert sha(W/'tools/native-review/methods/transport/native-transport-high.mjs')==l['actualTransportMethodSHA256']
 catalog=W/'tools/native-review/bundle-manifest.json';nb=native();assert load(catalog)['files']==nb and len(nb)==l['actualNativeBundleFileCount'] and sha(catalog)==l['actualNativeBundleManifestSHA256'];assert all(sha(W/p)==pin for p,pin in expected['assets'].items())
 tracked=[p for p in subprocess.check_output(['git','ls-files','-z'],cwd=W).decode().split('\0') if p];before={p:sha(W/p) for p in tracked};status=subprocess.check_output(['git','status','--porcelain','-z'],cwd=W);out=Path(a.output).resolve();assert not out.exists() and not out.is_relative_to(W);out.mkdir(parents=True);save(out,'all-tracked-hashes-before.json',before);save(out,'actual-source-hashes-before.json',source);save(out,'native-inventory-before.json',nb)
 env=os.environ.copy();env['GITHUB_SHA']=a.head;started=datetime.datetime.now(datetime.timezone.utc).isoformat();t=time.monotonic()
 with (out/'build.stdout.log').open('wb') as stdout,(out/'build.stderr.log').open('wb') as stderr:run=subprocess.run(['npm','run','build'],cwd=W,env=env,stdout=stdout,stderr=stderr)
 raw=(W/'dist/build-info.json').read_bytes();(out/'committed-build-info-original.json').write_bytes(raw);actual=json.loads(raw);after={p:sha(W/p) for p in tracked};asource={p:sha(W/p) for p in source};anative=native();save(out,'all-tracked-hashes-after.json',after);save(out,'actual-source-hashes-after.json',asource);save(out,'native-inventory-after.json',anative)
 checks={'buildExitZero':run.returncode==0,'allTrackedBeforeAfterFrozen':before==after,'allSourceBeforeAfterFrozen':source==asource,'nativeInventoryBeforeAfterFrozen':nb==anative and sha(catalog)==l['actualNativeBundleManifestSHA256'],'headTreeStatusFrozen':git('rev-parse','HEAD')==a.head and git('rev-parse','HEAD^{tree}')==a.tree and status==subprocess.check_output(['git','status','--porcelain','-z'],cwd=W),'actualRevisionHead':actual.get('revision')==a.head,'version08':actual.get('version')=='0.8.0','entireCurrentRuntimeDictionaryLiteralNullBuild':actual['assets']==expected['assets'] and len(actual['assets'])==l['actualResourceCount'],'allActualSourceDistHashesExact':all(sha(W/p)==sha(W/'dist'/p)==pin for p,pin in actual['assets'].items())}
 receipt={'status':'ACTUAL_COMMITTED_COMBINED_REFERENCE_BUILD_PASS_NATIVE_AND_ART_PENDING' if all(checks.values()) else 'ACTUAL_COMMITTED_COMBINED_REFERENCE_BUILD_FAILED_OUTPUTS_PRESERVED','commit':a.head,'tree':a.tree,'parent':PARENT,'actualResourceCount':len(actual['assets']),'actualBuildInfoSHA256':sha(out/'committed-build-info-original.json'),'actualNullBuildInfoSHA256':sha(np),'actualSourceFileCount':len(source),'actualNativeBundleFileCount':len(nb),'actualNativeBundleManifestSHA256':sha(catalog),'stageLedgerPath':str(lp),'stageLedgerSHA256':sha(lp),'sourceCatalog':{'path':str(sp),'sha256':sha(sp),'bytes':sp.stat().st_size},'trackedFiles':len(tracked),'assets':len(actual['assets']),'actualBuildSHA256':sha(out/'committed-build-info-original.json'),'sourceFiles':len(source),'nativeBundleFiles':len(nb),'nativeBundleManifestSHA256':sha(catalog),'checks':checks,'buildExit':run.returncode,'startedAtUTC':started,'elapsedSeconds':time.monotonic()-t,'stdoutSHA256':sha(out/'build.stdout.log'),'stderrSHA256':sha(out/'build.stderr.log'),'testsRerun':False,'GPUOrNetworkExecuted':False,'newNativeOrArtPassInherited':False};save(out,'receipt.json',receipt);print(json.dumps(receipt));return 0 if all(checks.values()) else 1
if __name__=='__main__':raise SystemExit(main())
