"""Prepare authorized exact-current metadata only. No production, tests, build, GPU, git or network execution."""
import ast,copy,hashlib,json
from pathlib import Path
W=Path('/workspace/neon-candidates/harbor-combined-transit-art-final-20261005');R=Path(str(W)+'-review');Q=W/'docs/qa/combined-transit-art-adoption-20261005';B=W/'tools/native-review';A=B/'runtime-amendments/combined-transit-art-final-20261005';CHECKS=Path('/workspace/neon-candidates/combined-transit-art-final-null-build-20261005');PARENT='220312885a7b1a7a987790aa4f9d1d38b294be90';MODULE='src/harbor-authored-transport-assets.js';TRAM={f'assets/harbor/transport/tram/vesper-t9-lod{i}.glb' for i in range(3)}
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def load(p):return json.loads(p.read_text())
def jb(v):return (json.dumps(v,ensure_ascii=False,indent=2)+'\n').encode()
def save(p,v):assert not p.exists(),p;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(jb(v))
def cp(p,t):assert not t.exists(),t;t.parent.mkdir(parents=True,exist_ok=True);t.write_bytes(p.read_bytes())
old=load(R/'original-native213-bundle-manifest-220.json');oldbuild=load(R/'original-committed-220208-build-info.json');olddicts=load(R/'original-expected-runtime-dictionaries-220.json');oldsource=load(R/'original-all401-source-hashes-220.json');build=load(CHECKS/'build-info-original.json');checks=load(CHECKS/'build-receipt.json');adopt=load(Q/'all-three-literal-adoption-receipt.json');nativeadopt=load(Q/'lower-photo-native-adoption-receipt.json');payload=adopt['literalTargetFiles'];source=load(CHECKS/'actual-source-hashes-before.json')
assert sha(CHECKS/'build-info-original.json')=='1822eed0866105128279f5150044c60e547750992ec69c79cb9ed67b1dcd0e51';assert sha(Q/'all-three-literal-adoption-receipt.json')=='efa6e66acaaade81f5930bab5c14876bff52fe28a193d6a9f571c7284960c88e';assert checks['status']=='ACTUAL_COMBINED_NULL_BUILD_PASS_NATIVE_AND_ART_PENDING' and all(checks['checks'].values());assert build['revision'] is None and build['version']=='0.8.0' and len(build['assets'])==208
assert set(checks['runtimeDeltaFrom220']['changed'])==TRAM|{MODULE} and checks['runtimeDeltaFrom220']['unchangedCount']==204 and not checks['runtimeDeltaFrom220']['added'] and not checks['runtimeDeltaFrom220']['removed'];assert len(source)==409 and {p:sha(W/p) for p in source}==source
for p,pin in build['assets'].items():assert sha(W/p)==sha(W/'dist'/p)==pin,p
for p,row in payload.items():assert sha(W/p)==row['sha256'] and (W/p).stat().st_size==row['bytes'],p
nativepaths={str(Path(p).relative_to('tools/native-review')) for p in nativeadopt['literalTargetFiles']}
for p,row in old['files'].items():
 if p not in nativepaths:assert sha(B/p)==row['sha256'] and (B/p).stat().st_size==row['bytes'],p
assert load(B/'expected-runtime-dictionaries.json')==olddicts
beforemeta={p:sha(B/p) for p in ['expected-runtime-dictionaries.json','methods/transport/runtime-resources.json','methods/transport-owner/runtime-resources.json','methods/transport/method-manifest.json','methods/transport-owner/method-manifest.json']}
# Preserve old active objects before replacing any current pin. Large actual art payload is already adopted once.
cp(R/'original-native213-bundle-manifest-220.json',A/'original-native213-bundle-manifest-220.json');cp(R/'original-expected-runtime-dictionaries-220.json',A/'original-expected-runtime-dictionaries-220.json');cp(R/'original-committed-220208-build-info.json',A/'original-committed-220208-build-info.json');cp(Q/'all-three-literal-adoption-receipt.json',A/'actual-all-three-literal-adoption-receipt.json')
for family in ['transport','transport-owner']:
 cp(B/'methods'/family/'runtime-resources.json',A/f'original-{family}-runtime-resources-220.json');cp(B/'methods'/family/'method-manifest.json',Q/'active-metadata-before'/f'{family}-method-manifest.json')
producer=Path('/workspace/neon-candidates/tram-waist-spandrel-seam-actual-cpu-export-20261005/final-runtime-source-identity-proof.json');assert sha(producer)=='bdf76fcf53f5e87535947876e2cd3088ee0288f2586e83d9f310af5f0a67e44b';cp(producer,A/'producer-actual-tram-source-identity-proof.json')
np=B/'expected-build-provenance/authored-build-info-combined-transit-art-final-20261005-1822eed08661.json';cp(CHECKS/'build-info-original.json',np)
d=copy.deepcopy(olddicts);d['authored']['assets']=build['assets'];d['authored']['currentBuildInfo']={'path':str(np.relative_to(B)),'sha256':sha(np),'bytes':np.stat().st_size,'version':'0.8.0','assetCount':208,'revision':None,'scope':'Actual single final combined null build: only3 Tram graphics GLBs and their3 expected SHA literals in one client asset module changed;204 runtime resources exact220. Separate E2E finite1080s reserve and explicit Bus/Tram immediate-boarded lower photo protocol. Original failures remain failures; new current functional/native/pixel validation required.'};assert d['baseline']==olddicts['baseline'];(B/'expected-runtime-dictionaries.json').write_bytes(jb(d))
bridge={'status':'EXACT_CURRENT_208_RESOURCE_FOUR_DELTA_SOURCE_BRIDGE_NATIVE_ART_PENDING','parentCommit':PARENT,'parentCommittedRawBuildInfoSHA256':sha(R/'original-committed-220208-build-info.json'),'currentActualNullBuildInfoSHA256':sha(np),'exactRuntimeDelta':checks['runtimeDeltaFrom220'],'actualAllRuntimeAssets':build['assets'],'oldSourceCount':401,'newActualSourceCount':409,'actualSourceManifestSHA256':sha(CHECKS/'actual-source-hashes-before.json'),'sourceDeltaFrom220':checks['sourceDeltaFrom220'],'sourceAddedFrom220':checks['sourceAddedFrom220'],'clientAssetModuleThreeSHALiteralReverseExactRequired':True,'actualProducerCPUProof':{'path':str((A/'producer-actual-tram-source-identity-proof.json').relative_to(B)),'sha256':sha(A/'producer-actual-tram-source-identity-proof.json')},'gameplayPhysicsTransitLifetimeClockResidentCameraInputRenderingLogicSourcesUnchangedExceptSHAList':True,'newTramRenderGeometryIsNotPixelIdentityToOldAssets':True,'originalExact208GraphicsBridgeInherited':False,'originalGeometricNativeCasesReexecutedBySealer':False,'newNativeArtOrPerformancePass':False,'actualCurrentDayNightQuartetAndFunctionalNativeGatesRequired':True};save(A/'actual-four-resource-and-source-bridge.json',bridge)
amend={'status':'EXPLICIT_CURRENT_COMBINED_SOURCE_METADATA_CPU_ONLY_NATIVE_ART_PENDING','parentCommit':PARENT,'originalNativeBundleManifestSHA256':sha(R/'original-native213-bundle-manifest-220.json'),'originalNativeFileCount':213,'runtimeBridgePath':str((A/'actual-four-resource-and-source-bridge.json').relative_to(B)),'runtimeBridgeSHA256':sha(A/'actual-four-resource-and-source-bridge.json'),'actualNullBuildInfoSHA256':sha(np),'runtimeDelta':checks['runtimeDeltaFrom220'],'testFunctionalReserve':{'originalMs':900000,'actualMs':1080000,'sourceSHA256':payload['tests/e2e/harbor-sample.spec.js']['sha256'],'actualNewCIRunRequired':True},'busTramLowerPhotoProtocol':{'activeMethodSHA256':payload['tools/native-review/methods/transport/native-transport-high.mjs']['sha256'],'literalAmendmentPath':'runtime-amendments/bus-tram-immediate-boarded-lower-photo-20261005/active-source-amendment.json','literalAmendmentSHA256':'fd71101fe398b0a77fc3c452bf6599101eb51aca393e67046f373aff57cc7a2d','upperActualOpenAndERefusalAndFinalDestinationRetained':True,'FerryAllBehaviorAndBudgetsUnchanged':True},'caseMatrixInputsCameraBodyMapsDeadlineAndQualityPoliciesUnchanged':True,'historicalProvenanceAndFailuresPreserved':True,'oldAcceptanceInherited':False,'nativeExecuted':False,'pixelArtAccepted':False};save(A/'combined-source-amendment.json',amend)
# Current resources only: three new Tram hashes/byte counts. Non-Tram rows, old enclosure/history fields remain deeply exact.
for family in ['transport','transport-owner']:
 folder=B/'methods'/family;rp=folder/'runtime-resources.json';resources=load(rp);before=copy.deepcopy(resources)
 for row in resources['files']:
  if row['target'] in TRAM:row['sha256']=build['assets'][row['target']];row['bytes']=(W/row['target']).stat().st_size;row['source']='art-source/transport/tram/models/'+Path(row['target']).name
 assert [x for x in resources['files'] if x['kind']!='tram']==[x for x in before['files'] if x['kind']!='tram'];assert resources.get('upperEnclosureAmendment')==before.get('upperEnclosureAmendment')
 resources['tramWaistSpandrelSeamAssetPinAmendment']={'path':str((A/'combined-source-amendment.json').relative_to(B)),'sha256':sha(A/'combined-source-amendment.json'),'oldResourcesPath':str((A/f'original-{family}-runtime-resources-220.json').relative_to(B)),'oldResourcesSHA256':sha(A/f'original-{family}-runtime-resources-220.json'),'oldSourceAndUpperEnclosureRecordsHistorical':True,'nativePending':True};rp.write_bytes(jb(resources))
 mp=folder/'method-manifest.json';m=load(mp);originalm=copy.deepcopy(m);m['resources']['sha256']=sha(rp)
 for field in ['sourcePins','authoredSourcePins','servedSourcePins']:
  if MODULE in m.get(field,{}):assert m[field][MODULE]==oldbuild['assets'][MODULE];m[field][MODULE]=build['assets'][MODULE]
 m['tramSeamCurrentResourceAndClientSHAAmendment']={'path':str((A/'combined-source-amendment.json').relative_to(B)),'sha256':sha(A/'combined-source-amendment.json'),'actualAssetModuleSHA256':build['assets'][MODULE],'historicalUpperEnclosureAmendmentRetainedVerbatim':True,'toolCodeChangedByThisMetadataRefresh':False,'nativePending':True};assert m.get('upperEnclosureAssetAmendment')==originalm.get('upperEnclosureAssetAmendment');mp.write_bytes(jb(m))
# Explicit post-preparation SHA map is the guard for the copied sealer; no arbitrary files/counts accepted.
files={str(p.relative_to(B)):{'sha256':sha(p),'bytes':p.stat().st_size} for p in sorted(B.rglob('*')) if p.is_file() and p!=B/'bundle-manifest.json'};assert not any(p.is_symlink() or '__pycache__' in p.parts or p.suffix=='.pyc' for p in B.rglob('*'))
receipt={'status':'ACTUAL_FOUR_RESOURCE_COMBINED_METADATA_PREPARED_NATIVE_ART_PENDING','parentCommit':PARENT,'actualNullBuildInfoSHA256':sha(np),'actualResourceCount':208,'runtimeDeltaFrom220':checks['runtimeDeltaFrom220'],'actualRuntimeAssets':build['assets'],'actualSourceCount':409,'actualSourceManifestPath':str(CHECKS/'actual-source-hashes-before.json'),'actualSourceManifestSHA256':sha(CHECKS/'actual-source-hashes-before.json'),'originalNative213ManifestSHA256':sha(R/'original-native213-bundle-manifest-220.json'),'actualExpectedNativeFileCount':len(files),'actualExpectedNativeFiles':files,'literalPayloadFiles':payload,'literalNativePayloadFiles':nativeadopt['literalTargetFiles'],'explicitActiveMetadataChangedPaths':sorted(beforemeta),'activeMetadataBeforePins':beforemeta,'bridgePath':str((A/'actual-four-resource-and-source-bridge.json').relative_to(B)),'bridgeSHA256':sha(A/'actual-four-resource-and-source-bridge.json'),'amendmentPath':str((A/'combined-source-amendment.json').relative_to(B)),'amendmentSHA256':sha(A/'combined-source-amendment.json'),'nativeOrArtPass':False};save(R/'combined-metadata-preparation-receipt.json',receipt)
src=Path('/workspace/neon-candidates/harbor-ferry-long-corridor-verification-final-20261005-review/strict-native-only-ferry-source-pin-sealer-identity-status.py');assert sha(src)=='7c346a0f73a9c0d84d38e52f606cd309db88cc2e27340ce880825599ba684107';script=src.read_text();start=script.index(' # Strict exact runtime identity;');end=script.index(" problem(build['assets']==authored['assets']",start)
guard=f''' # Strict actual four-resource/source bridge, with fixed complete inventory and immutable history.
 final_receipt_path=Path({str(R/'combined-metadata-preparation-receipt.json')!r});problem(digest(final_receipt_path)=={sha(R/'combined-metadata-preparation-receipt.json')!r},'Actual combined metadata receipt changed');final_receipt=load(final_receipt_path)
 problem(final_receipt['status']=='ACTUAL_FOUR_RESOURCE_COMBINED_METADATA_PREPARED_NATIVE_ART_PENDING','Explicit combined scope missing')
 problem(build['assets']==final_receipt['actualRuntimeAssets'] and len(build['assets'])==208,'Actual entire208 current dictionary changed')
 problem(set(final_receipt['runtimeDeltaFrom220']['changed'])=={{'assets/harbor/transport/tram/vesper-t9-lod0.glb','assets/harbor/transport/tram/vesper-t9-lod1.glb','assets/harbor/transport/tram/vesper-t9-lod2.glb','src/harbor-authored-transport-assets.js'}} and final_receipt['runtimeDeltaFrom220']['unchangedCount']==204 and not final_receipt['runtimeDeltaFrom220']['added'] and not final_receipt['runtimeDeltaFrom220']['removed'],'Explicit4/204/no-add-remove bridge changed')
 for rel,pin in final_receipt['actualRuntimeAssets'].items():problem(digest(contained(w,rel))==digest(contained(w/'dist',rel))==pin,'Current resource/source/dist differs:'+rel)
 source_path=Path(final_receipt['actualSourceManifestPath']);problem(digest(source_path)==final_receipt['actualSourceManifestSHA256'],'Actual source409 manifest changed');source=load(source_path)
 problem(len(source)==409 and all(digest(contained(w,p))==pin for p,pin in source.items()),'Actual final409 source changed during metadata sealing')
 original_catalog=load(b/'runtime-amendments/combined-transit-art-final-20261005/original-native213-bundle-manifest-220.json');problem(digest(b/'runtime-amendments/combined-transit-art-final-20261005/original-native213-bundle-manifest-220.json')==final_receipt['originalNative213ManifestSHA256'],'Original213 catalog history changed')
 old_dictionaries=load(b/'runtime-amendments/combined-transit-art-final-20261005/original-expected-runtime-dictionaries-220.json');problem(baseline==old_dictionaries['baseline'],'Baseline156 deep dictionary changed')
 permitted_old_changes=set(final_receipt['explicitActiveMetadataChangedPaths'])|{{str(Path(p).relative_to('tools/native-review')) for p in final_receipt['literalNativePayloadFiles']}}
 for rel,row in original_catalog['files'].items():
  if rel not in permitted_old_changes:problem(digest(contained(b,rel))==row['sha256'],'Historical/functional native213 file unexpectedly changed:'+rel)
 for rel,row in final_receipt['literalPayloadFiles'].items():
  if rel!='tools/native-review/methods/transport/method-manifest.json':problem(digest(contained(w,rel))==row['sha256'] and contained(w,rel).stat().st_size==row['bytes'],'Reviewed literal payload changed:'+rel)
 actual_native={{str(p.relative_to(b)):{{'sha256':digest(p),'bytes':p.stat().st_size}} for p in b.rglob('*') if p.is_file() and p!=b/'bundle-manifest.json'}}
 problem(actual_native==final_receipt['actualExpectedNativeFiles'] and len(actual_native)=={len(files)},'Complete current nativeinventory differs from actual sealed{len(files)} files')
 problem(not any(p.is_symlink() or '__pycache__' in p.parts or p.suffix=='.pyc' for p in b.rglob('*')),'Bundle cannot admit caches or symlinks')
 notes.append('Actual208 runtime4delta/204same and409source frozen.3GLB geometry and3 clientSHA literals changed; explicit E2E1080s reserve and reviewed BusTram lower dock-or-travel photo protocol. Old outputs retain their outcomes; new native/art evidence required. No geometry case or GPU reexecution by sealer.')
'''
script=script[:start]+guard+script[end:]
line=next(x for x in script.splitlines() if x.startswith(" catalog['ferrySourceAxisAndFiniteLongHallNativeMethodAmendment']="));script=script.replace(line," problem(catalog['ferrySourceAxisAndFiniteLongHallNativeMethodAmendment']==original_catalog['ferrySourceAxisAndFiniteLongHallNativeMethodAmendment'],'Original Ferry ce3/source bridge history changed')")
script=script.replace('refreshChangedRuntimeSource=False','refreshChangedRuntimeSource=True')
insert=" catalog['combinedTransitSeamAndVerificationReferenceAmendment']={'status':'ACTUAL_SOURCE_AND_PROTOCOL_METADATA_NATIVE_ART_PENDING','parentCommit':final_receipt['parentCommit'],'parentNativeFileCount':213,'parentNativeManifestSHA256':final_receipt['originalNative213ManifestSHA256'],'actualNativeFileCount':final_receipt['actualExpectedNativeFileCount'],'actualNullBuildInfoSHA256':final_receipt['actualNullBuildInfoSHA256'],'runtimeDeltaFrom220':final_receipt['runtimeDeltaFrom220'],'actualSourceFileCount':final_receipt['actualSourceCount'],'bridgePath':final_receipt['bridgePath'],'bridgeSHA256':final_receipt['bridgeSHA256'],'sourceAmendmentPath':final_receipt['amendmentPath'],'sourceAmendmentSHA256':final_receipt['amendmentSHA256'],'allOldOutcomesPreserved':True,'newNativeOrArtPass':False}\n"
script=script.replace(" catalog['activityPinRefresh']=",insert+" catalog['activityPinRefresh']=",1);ast.parse(script);dst=R/'strict-combined-four-runtime-source-pin-sealer.py';assert not dst.exists();dst.write_text(script)
save(R/'strict-combined-sealer-derivation-receipt.json',{'status':'STRICT_NEW_COPY_WITH_EXPLICIT_FOUR_RESOURCE_AND409SOURCE_FULL_INVENTORY_GUARD','originalSealerSHA256':sha(src),'newSealerSHA256':sha(dst),'oldGuardCompletelyReplaced':True,'actualNativeFileCount':len(files),'fixedBaselineAndWorkflowCaseQualityBudgetGuardsRetained':True,'noProductionFilesChanged':{p:sha(W/p) for p in source}==source,'testsBuildGPUOrNetworkExecuted':False})
print(json.dumps({'status':'PREPARED_ACTUAL_CURRENT_METADATA_NO_NEW_NATIVE_PASS','receipt':str(R/'combined-metadata-preparation-receipt.json'),'receiptSHA256':sha(R/'combined-metadata-preparation-receipt.json'),'sealer':str(dst),'sealerSHA256':sha(dst),'actualNativeFiles':len(files),'expectedDictionarySHA256':sha(B/'expected-runtime-dictionaries.json')}))
