"""ROOT-authorized native metadata only after literal payload/reference materialization. No source/test/build/stage/GPU/network writes."""
import ast,hashlib,json
from pathlib import Path
P=Path('/workspace/neon-candidates/ferry-fresh-public-aim-native-only-sealer-preparation-20261005');W=Path('/workspace/neon-candidates/harbor-ferry-relative-aim-final-20261005');R=Path('/workspace/neon-candidates/harbor-ferry-relative-aim-final-20261005-root-review');B=W/'tools/native-review';Q=W/'docs/qa/ferry-observed-public-aim-adoption-20261005';A=B/'runtime-amendments/ferry-observed-one-frame-public-aim-20261005';C=Path('/workspace/neon-candidates/ferry-observed-one-frame-public-aim-candidate-20261005');PARENT='15c692eae329b8eaa8d5aba9ada4149e6b5bec79'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def load(p):return json.loads(p.read_text())
def jb(v):return (json.dumps(v,ensure_ascii=False,indent=2)+'\n').encode()
def save(p,v):assert not p.exists(),p;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(jb(v))
def cp(p,t):assert not t.exists(),t;t.parent.mkdir(parents=True,exist_ok=True);t.write_bytes(p.read_bytes())
facts=load(P/'actual15c-parent-bound-interface.json');assert sha(P/'actual15c-parent-bound-interface.json')=='157f93de69c86e28a7e415dfef007ade0175c165001fe1440f3aec224e3f8bf2'
root_receipt=R/'ROOT_ADOPTION_RECEIPT.json';assert sha(root_receipt)=='89d9bd7cc632337bc105e3cc112481f40eff82ad0cbd99b41bff1cf4eb97b3cd';adopt=load(root_receipt);assert adopt['status']=='ROOT_LITERAL_THREE_PAYLOAD_AND_CLOSED_PROOF_ADOPTION_NATIVE_PENDING' and adopt['parent']==PARENT and adopt['candidateManifestSha256']=='dc1a248457a61a99f1056c43b256110e114c43c377204d9bb962fca47c7eaf86'
material=R/'ROOT_LITERAL_PARENT_REFERENCE_72_GENERATED_AND_209_DIST_MATERIALIZATION.json';assert sha(material)=='53c634d34e74f8cc87e0521f5a2ed7c7e9491942d27c08fc223b787abb527870'
reverse=R/'ROOT_ACTUAL_WHOLE_SOURCE_REVERSAL_AND_NESTED_REVIEW_GUARDS.json';assert sha(reverse)=='955966a3e381def345a4b7072bc4a55f051acec6238161b6b089cd068ab9d973'
assert sha(C/'SEAL.json')=='76733324e9d7bfb35edc7d1b5749ebc3b3e9d032e607146ef7185f7320ffa9eb';assert sha(C/'PAYLOAD_MANIFEST.json')=='dc1a248457a61a99f1056c43b256110e114c43c377204d9bb962fca47c7eaf86'
for row in load(C/'SEAL.json')['inventory']:assert sha(C/row['path'])==row['sha256'] and (C/row['path']).stat().st_size==row['bytes']
payload={row['target']:{'bytes':row['candidate']['bytes'],'sha256':row['candidate']['sha256']} for row in adopt['payload']};assert len(payload)==3
for p,row in payload.items():assert sha(W/p)==row['sha256'] and (W/p).stat().st_size==row['bytes'],p
for p,row in adopt['copiedOriginalProofs'].items():assert sha(W/p)==row['sha256'] and (W/p).stat().st_size==row['bytes'],p
source_path=Path(facts['parentSourceCatalog']['path']);assert sha(source_path)==facts['parentSourceCatalog']['sha256'];source=load(source_path);assert len(source)==409 and {p:sha(W/p) for p in source}==source
bp=Path(facts['parentActualCommittedBuildInfo']['path']);assert sha(bp)==facts['parentActualCommittedBuildInfo']['sha256'];build=load(bp);assert len(build['assets'])==208 and build['revision']==PARENT
for p,pin in build['assets'].items():assert sha(W/p)==sha(W/'dist'/p)==pin,p
assert sha(W/'dist/build-info.json')==facts['parentActualCommittedBuildInfo']['sha256'],'Literal materialized raw reference, not newly claimed build'
parent_native=Path(facts['parentNativeCatalog']['path']);assert sha(parent_native)==facts['parentNativeCatalog']['sha256'];old=load(parent_native);assert len(old['files'])==224
allow={'methods/transport/native-transport-high.mjs','methods/transport/method-manifest.json'}
for p,row in old['files'].items():
 if p not in allow:assert sha(B/p)==row['sha256'] and (B/p).stat().st_size==row['bytes'],p
assert sha(B/'expected-runtime-dictionaries.json')==facts['parentExpectedRuntimeDictionary']['sha256'];cp(parent_native,A/'original-native224-bundle-manifest-15c.json');cp(root_receipt,A/'actual-root-literal-adoption-receipt.json')
bridge={'status':'ACTUAL_EXACT15C208_GRAPHICS_RESOURCE_AND409_SOURCE_IDENTITY_NATIVE_ONLY_BRIDGE','parentCommit':PARENT,'parentCommittedRawBuildInfoSHA256':facts['parentActualCommittedBuildInfo']['sha256'],'sourceCatalog':facts['parentSourceCatalog'],'runtimeResourceCount':208,'sourceFileCount':409,'runtimeDeltaRelative15c':{'changed':[],'added':[],'removed':[],'unchangedCount':208},'actual208SourceAndMaterializedDistEachSHAExact15c':True,'materializedBuildRawSHA256':sha(W/'dist/build-info.json'),'referenceMaterializationIsNotNewBuild':True,'referenceMaterializationReceiptSHA256':sha(material),'all409SourceBytesExact15c':True,'old4RuntimeDeltaRelative220IsUnmodifiedHistory':True,'original15cPhotoSubjectsAndArtDecisionsNotRelabeledAsNewCapture':True,'exactGraphicsOnlyScope':'Same208 graphics inputs/409source permits original15c graphics evidence only within each original capture and human review scope; new Ferry native execution remains mandatory.','literalNativePayloads':payload,'original220HighFailureRemainsFailure':True,'blocked240055AndInitial517PressureFailuresPreserved':True,'newNativeOrArtApproval':False};save(A/'actual-exact15c208-and409-source-bridge.json',bridge)
files={str(p.relative_to(B)):{'bytes':p.stat().st_size,'sha256':sha(p)} for p in sorted(B.rglob('*')) if p.is_file() and p!=B/'bundle-manifest.json'};assert not any(p.is_symlink() or '__pycache__' in p.parts or p.suffix=='.pyc' for p in B.rglob('*'))
meta={'status':'ACTUAL_FERRY_FRESH_PUBLIC_AIM_NATIVE_ONLY_METADATA_PREPARED_RUNTIME_ZERO_DELTA','parentCommit':PARENT,'parentNativeManifestSHA256':sha(parent_native),'parentNativeFileCount':224,'approvedCandidateManifestSHA256':'dc1a248457a61a99f1056c43b256110e114c43c377204d9bb962fca47c7eaf86','actualCurrentMethodSHA256':payload['tools/native-review/methods/transport/native-transport-high.mjs']['sha256'],'explicitNativePayloadFiles':payload,'actualExpectedNativeFiles':files,'actualExpectedNativeFileCount':len(files),'runtimeDeltaRelative15c':bridge['runtimeDeltaRelative15c'],'source409Literal15c':True,'runtimeExpectedDictionaryLiteral15c':True,'resourcesOwnersCanonicalCaseBudgetsQualityWorkflowsHistoricalRowsLiteral15c':True,'bridgePath':str((A/'actual-exact15c208-and409-source-bridge.json').relative_to(B)),'bridgeSHA256':sha(A/'actual-exact15c208-and409-source-bridge.json'),'rootAdoptionSHA256':sha(root_receipt),'rootMaterializationSHA256':sha(material),'rootWholeReverseGuardSHA256':sha(reverse),'nativeOrArtPass':False};mp=R/'ACTUAL_OBSERVED_FERRY_NATIVE_ONLY_METADATA_PREPARATION.json';save(mp,meta)
t=P/'strict-native-only-ferry-fresh-public-aim-sealer.template.py';assert sha(t)=='0c48ff169e40e679d007a18a67c6afb3dfb4a21e309d995c1c31e2106f8d72b8';s=t.read_text();s=s.replace('APPROVED_CANDIDATE_MANIFEST_SHA256=None',"APPROVED_CANDIDATE_MANIFEST_SHA256='dc1a248457a61a99f1056c43b256110e114c43c377204d9bb962fca47c7eaf86'");s=s.replace('FUTURE_METADATA_RECEIPT_SHA256=None',f'FUTURE_METADATA_RECEIPT_SHA256={sha(mp)!r}');s=s.replace('FUTURE_NATIVE_FILE_COUNT=None',f'FUTURE_NATIVE_FILE_COUNT={len(files)}');s=s.replace(str(P/'FUTURE_FINAL_NATIVE_ONLY_METADATA_RECEIPT.json'),str(mp));ast.parse(s);dst=R/'strict-final-observed-ferry-native-only-source-pin-sealer.py';assert not dst.exists();dst.write_text(s)
for p in [root_receipt,material,reverse]:
 target=Q/'metadata-review'/p.name
 if not target.exists():cp(p,target)
print(json.dumps({'status':'ACTUAL_PREPARED_METHOD_ONLY_SOURCE_ZERO_METADATA_NATIVE_PENDING','nativeFileCount':len(files),'metadataReceipt':str(mp),'metadataReceiptSHA256':sha(mp),'sealer':str(dst),'sealerSHA256':sha(dst),'ownerResourcesOrExpectedDictionaryChanged':False,'source409AndRuntime208ActualVerified':True}))
