"""ROOT-only one committed revision build after exact reviewed final isolated source/tools commit."""
import argparse,datetime,hashlib,json,os,re,subprocess,time
from pathlib import Path
ROOT=Path('/workspace/neon-candidates/harbor-material-lighting-final-20261005');REVIEW=Path('/workspace/neon-candidates/harbor-material-lighting-final-20261005-review');PARENT='ef4112bed4624c9c969b5b5f3746ccbfb64817aa';NULL='c6b72d9e690fea559643cbe7da74523618a1812fd3484dd1091833cc95ed98a2';SOURCE_SHA='c7b3213b4287a4b136a8e1d427170c6920088ab6fb7f6cce9407219d225e871b';REFERENCE=REVIEW/'final-idle-production-checks/build-info-original.json';SOURCE=REVIEW/'final-idle-production-checks/all-production-test-source-hashes-after.json'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def git(*args):return subprocess.check_output(['git',*args],cwd=ROOT,text=True).strip()
def load(p):return json.loads(p.read_text())
def save(out,name,value):p=out/name;assert not p.exists(),p;p.write_text(json.dumps(value,ensure_ascii=False,indent=2)+'\n')
def native_map():
 b=ROOT/'tools/native-review';assert not any(p.is_symlink() or '__pycache__' in p.parts or p.suffix=='.pyc' for p in b.rglob('*'))
 return {str(p.relative_to(b)):{'sha256':sha(p),'bytes':p.stat().st_size} for p in sorted(b.rglob('*')) if p.is_file() and p!=b/'bundle-manifest.json'}
def main():
 ap=argparse.ArgumentParser(description=__doc__);ap.add_argument('--head',required=True);ap.add_argument('--tree',required=True);ap.add_argument('--stage-ledger',required=True);ap.add_argument('--stage-ledger-sha256',required=True);ap.add_argument('--output',required=True);a=ap.parse_args();assert all(re.fullmatch('[0-9a-f]{40}',v) for v in [a.head,a.tree]) and re.fullmatch('[0-9a-f]{64}',a.stage_ledger_sha256)
 out=Path(a.output).resolve();assert not out.exists() and not out.is_relative_to(ROOT)
 assert git('rev-parse','HEAD')==a.head and git('rev-parse','HEAD^{tree}')==a.tree and a.head!=PARENT and git('rev-list','--parents','-n','1',a.head).split()==[a.head,PARENT]
 assert not subprocess.check_output(['git','status','--porcelain','--untracked-files=no'],cwd=ROOT)
 ledgerpath=Path(a.stage_ledger);assert sha(ledgerpath)==a.stage_ledger_sha256;ledger=load(ledgerpath);assert ledger['status']=='ACTUAL_FINAL_SOURCE_AND_METADATA_STAGE_READY_NATIVE_ART_PENDING' and ledger['parentCommit']==PARENT and ledger['actualSourceFileCount']==401 and ledger['actualNullBuildInfoSHA256']==NULL
 changed=git('diff','--name-only',PARENT,a.head).splitlines();assert set(changed)==set(ledger['files']) and len(changed)==len(ledger['files'])
 for p,row in ledger['files'].items():assert sha(ROOT/p)==row['sha256'] and (ROOT/p).stat().st_size==row['bytes'],p
 assert sha(REFERENCE)==NULL and sha(SOURCE)==SOURCE_SHA;expected=load(REFERENCE);source=load(SOURCE);assert expected.get('revision') is None and expected['version']=='0.8.0' and len(expected['assets'])==208 and len(source)==401
 assert {p:sha(ROOT/p) for p in source}==source and all(sha(ROOT/p)==pin for p,pin in expected['assets'].items())
 dictionaries=load(ROOT/'tools/native-review/expected-runtime-dictionaries.json');assert dictionaries['authored']['assets']==expected['assets'];assert dictionaries['baseline']==load(ROOT/'docs/qa/material-lighting-adoption-20261005/original-expected-runtime-dictionaries-ef411.json')['baseline'] and len(dictionaries['baseline']['assets'])==156
 catalogpath=ROOT/'tools/native-review/bundle-manifest.json';assert sha(catalogpath)==ledger['actualNativeBundleManifestSHA256'];catalog=load(catalogpath);nbefore=native_map();assert catalog['files']==nbefore and len(nbefore)==ledger['actualNativeBundleFileCount']
 paths=[p for p in subprocess.check_output(['git','ls-files','-z'],cwd=ROOT).decode().split('\0') if p];assert len(paths)==len(set(paths)) and all((ROOT/p).is_file() and not (ROOT/p).is_symlink() for p in paths)
 status=subprocess.check_output(['git','status','--porcelain','-z'],cwd=ROOT);before={p:sha(ROOT/p) for p in paths};source_before={p:sha(ROOT/p) for p in source};out.mkdir(parents=True)
 save(out,'all-tracked-hashes-before.json',before);save(out,'all401-source-hashes-before.json',source_before);save(out,'entire-native-inventory-before.json',nbefore);(out/'null-revision-build-info-original.json').write_bytes(REFERENCE.read_bytes())
 env=os.environ.copy();env['GITHUB_SHA']=a.head;started=datetime.datetime.now(datetime.timezone.utc).isoformat();tick=time.monotonic()
 with (out/'build.stdout.log').open('wb') as stdout,(out/'build.stderr.log').open('wb') as stderr:run=subprocess.run(['npm','run','build'],cwd=ROOT,env=env,stdout=stdout,stderr=stderr)
 elapsed=time.monotonic()-tick;raw=(ROOT/'dist/build-info.json').read_bytes();(out/'committed-build-info-original.json').write_bytes(raw)
 after={p:sha(ROOT/p) for p in paths};source_after={p:sha(ROOT/p) for p in source};nafter=native_map();save(out,'all-tracked-hashes-after.json',after);save(out,'all401-source-hashes-after.json',source_after);save(out,'entire-native-inventory-after.json',nafter);actual=json.loads(raw)
 checks={'buildExitZero':run.returncode==0,'allActualTrackedFilesFrozen':before==after,'all401SourceBeforeAfterEqual':source_before==source_after,'entireNativeInventoryFrozen':nbefore==nafter and sha(catalogpath)==ledger['actualNativeBundleManifestSHA256'],'headTreeParentFrozen':git('rev-parse','HEAD')==a.head and git('rev-parse','HEAD^{tree}')==a.tree and git('rev-list','--parents','-n','1',a.head).split()==[a.head,PARENT],'gitStatusFrozen':status==subprocess.check_output(['git','status','--porcelain','-z'],cwd=ROOT),'actualRevisionEqualsNewHEAD':actual.get('revision')==a.head,'actualVersionPreserved':actual.get('version')==expected['version'],'entire208DictionaryEqualsTestedFinalNullC6b72':actual.get('assets')==expected['assets'] and len(actual.get('assets',{}))==208,'all208ActualSourceAndDistBytesMatch':all(sha(ROOT/p)==sha(ROOT/'dist'/p)==pin for p,pin in actual['assets'].items())}
 receipt={'status':'ACTUAL_COMMITTED_FINAL_MATERIAL_LIGHTING_BUILD_PASS_NATIVE_ART_PENDING' if all(checks.values()) else 'ACTUAL_COMMITTED_FINAL_BUILD_REJECTED_OR_FAILED_ORIGINAL_OUTPUTS_PRESERVED','commit':a.head,'tree':a.tree,'parent':PARENT,'assets':len(actual['assets']),'actualBuildSHA256':hashlib.sha256(raw).hexdigest(),'nullBuildSHA256':NULL,'trackedFiles':len(before),'sourceFiles':len(source_before),'nativeBundleFiles':len(nbefore),'nativeBundleManifestSHA256':sha(catalogpath),'stageLedgerPath':str(ledgerpath),'stageLedgerSHA256':sha(ledgerpath),'checks':checks,'rulesAlreadyVerified':381,'actualFinalFull381ReceiptSHA256':sha(REVIEW/'final-idle-production-checks/full-npm-test-receipt.json'),'testsRerun':False,'buildCommand':['npm','run','build'],'buildRepeatedForThisCommittedSource':False,'buildExit':run.returncode,'startedAtUTC':started,'elapsedSeconds':elapsed,'stdoutSHA256':sha(out/'build.stdout.log'),'stderrSHA256':sha(out/'build.stderr.log'),'createdAtUTC':datetime.datetime.now(datetime.timezone.utc).isoformat(),'sourceOrMethodFilesWritten':False,'nativeGpuOrNetworkExecuted':False,'nativeOrArtAccepted':False};save(out,'receipt.json',receipt);print(json.dumps(receipt));return 0 if all(checks.values()) else 1
if __name__=='__main__':raise SystemExit(main())
