import datetime,hashlib,json,subprocess
from pathlib import Path
w=Path('/workspace/neon-candidates/harbor-transit-compact-verification-final-20261005');r=Path('/workspace/neon-candidates/harbor-transit-compact-verification-final-20261005-review');q=w/'docs/qa/transit-compact-verification-20261005';c=Path('/workspace/neon-candidates/required-ferry-compact-snapshot-candidate-20261005');parent=Path('/workspace/neon-candidates/harbor-visible-west-ridge-final-20261005')
head='b80eace6b3cf62eea3589c6dda40ed16251b480c';target='tests/e2e/harbor-sample.spec.js'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def load(p):return json.loads(p.read_text())
def save(p,v):assert not p.exists(),p;p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
def cp(p,t):assert not t.exists(),t;t.parent.mkdir(parents=True,exist_ok=True);t.write_bytes(p.read_bytes())
assert subprocess.check_output(['git','rev-parse','HEAD'],cwd=w,text=True).strip()==head
assert sha(c/'SEAL.json')=='947cc23bc949d7b2e22777b1b2b4e364757b2155bc3acf206bda546537176375'
assert sha(c/'PAYLOAD_MANIFEST.json')=='a4ba826ce047035f51aafeed7cbce943356eea2ca1601b964e300c964d346ae7'
seal=load(c/'SEAL.json');assert len(seal['files'])==11 and len({x['path'] for x in seal['files']})==11
for row in seal['files']:
 p=c/row['path'];assert not p.is_symlink() and sha(p)==row['sha256'] and p.stat().st_size==row['bytes'],p
m=load(c/'PAYLOAD_MANIFEST.json');assert m['sourceParentForAdoption']==head and len(m['payload'])==1 and m['payload'][0]['path']==target
row=m['payload'][0];src=c/'payload'/target;assert sha(src)==row['sha256']=='48bacdf2e79dc4eaacf0e474362c60bdfdc33863706d57759bc53ce0bc38518f'
original=(w/target).read_text();candidate=src.read_text();assert sha(w/target)==sha(parent/target)==m['expectedOriginalTestSHA256']=='9f0dd470f17cfa8ec5b84e1079b64429de976fc06caaa501662e11e454ce5476'
helper="""    // Return only the fields consumed by this transit scenario. The complete
    // transit state and all physical alighting assertions remain unchanged.
    const transitSnapshot = () => page.evaluate(() => {
      const s = window.__NEON__.snapshot();
      return { position: s.position, simulationTime: s.simulationTime, teleportRevision: s.teleportRevision,
        city: { sample: { transit: s.city.sample.transit }, interior: { buildingId: s.city.interior.buildingId } } };
    });
"""
assert candidate.count(helper)==1 and candidate.count('transitSnapshot()')==10
reversed_candidate=candidate.replace(helper,'').replace('transitSnapshot()','snapshot(page)');assert reversed_candidate==original
cpu=load(c/'CPU.stdout.json');assert cpu['status']=='PASS_CPU_ONLY' and cpu['realOriginalSnapshotCount']==13 and all(x['allConsumedFieldsExact'] and x['snapshotCalls']==1 for x in cpu['rows'])
assert cpu['originalPostEAlightingObserved'] and cpu['budgetsAndInputsUnchanged'] and cpu['newNativeResult'] is None
assert not q.exists();q.mkdir(parents=True)
for row in seal['files']:
 if not row['path'].startswith('payload/'):cp(c/row['path'],q/'original-sealed-candidate-proof'/row['path'])
cp(c/'SEAL.json',q/'original-sealed-candidate-proof/SEAL.json')
for n in ['preparation-receipt.json','ignored-runtime-materialization-receipt.json']:cp(r/n,q/n)
save(q/'readonly-preflight-shape-history.json',{'status':'EXTERNAL_INSPECTION_ONLY_SCHEMA_REJECTION_NOT_PRODUCT_FAILURE','error':'A generic initial inspection attempted PAYLOAD_MANIFEST.files; actual sealed single-payload schema uses payload. Read failed before any test payload adoption. Corrected parser reads exact original payload key. Candidate originals unchanged.','nonexistentSummaryRead':'A guessed CPU-SUMMARY.json filename was absent; actual sealed CPU.stdout.json and closed-original-first-failure.json used. No execution or file write depended on that read.'})
tracked=[p for p in subprocess.check_output(['git','ls-files','-z'],cwd=w).decode().split('\0') if p];before={p:sha(w/p) for p in tracked};save(r/'all-tracked-hashes-before.json',before)
source_before=load(parent/'docs/qa/visible-western-ridge-adoption-20261005/all-production-test-source-hashes-after.json');assert source_before=={p:sha(w/p) for p in source_before};save(q/'all396-production-test-source-hashes-before.json',source_before)
(w/target).write_bytes(src.read_bytes());assert sha(w/target)==row['sha256']
syntax=subprocess.run(['node','--check',str(w/target)],capture_output=True);(q/'node-check.stdout.raw').write_bytes(syntax.stdout);(q/'node-check.stderr.raw').write_bytes(syntax.stderr);assert syntax.returncode==0
after={p:sha(w/p) for p in tracked};save(r/'all-tracked-hashes-after.json',after);changed=[p for p in before if before[p]!=after[p]];assert changed==[target]
source_after={p:sha(w/p) for p in source_before};assert [p for p in source_before if source_before[p]!=source_after[p]]==[target];save(q/'all396-production-test-source-hashes-after.json',source_after)
b=w/'tools/native-review';expected=load(b/'expected-runtime-dictionaries.json');runtime=expected['authored']['assets'];assert len(runtime)==207
for p,pin in runtime.items():assert sha(w/p)==sha(parent/p)==pin,p
catalog=load(b/'bundle-manifest.json');assert len(catalog['files'])==184 and sha(b/'bundle-manifest.json')=='b7c421a8022bf41f8c4300cf80da96921fd8416ea61f66a4cf0ea85417706fcd'
actual={str(p.relative_to(b)):{'bytes':p.stat().st_size,'sha256':sha(p)} for p in b.rglob('*') if p.is_file() and p!=b/'bundle-manifest.json'};assert actual==catalog['files']
assert sha(w/'.github/workflows/ci.yml')==sha(parent/'.github/workflows/ci.yml') and sha(w/'.github/workflows/native-art.yml')==sha(parent/'.github/workflows/native-art.yml') and sha(w/'.github/workflows/pages.yml')==sha(parent/'.github/workflows/pages.yml')
receipt={'status':'ACTUAL_LITERAL_COMPACT_TRANSIT_TEST_ONLY_ADOPTED_NEW_REQUIRED_BROWSER_RUN_PENDING','atUTC':datetime.datetime.now(datetime.timezone.utc).isoformat(),'parentCommit':head,'worktree':str(w),'payloadFile':target,'actualOriginalTestSHA256':m['expectedOriginalTestSHA256'],'actualAdoptedTestSHA256':row['sha256'],'candidateSealSHA256':sha(c/'SEAL.json'),'candidatePayloadManifestSHA256':sha(c/'PAYLOAD_MANIFEST.json'),'all11SealedCandidateFilesVerified':True,'literalHelperAnd10CallsiteReverseEqualsOriginalB80And8b':True,'allOriginalAssertionsBudgetsInputsCamerasAndOtherTestsBytePreserved':True,'actualOriginal13SnapshotCPUReceiptSHA256':sha(c/'CPU.stdout.json'),'candidateOriginalCPUNotReexecutedByAdopter':True,'originalPostEOutsidePositionAndRidingFalseEvidenceRetained':True,'trackedFileCountBefore':len(before),'onlyTrackedFileChanged':target,'allOtherTrackedFileCountExactB80':len(before)-1,'externalFullTrackedBeforePath':str(r/'all-tracked-hashes-before.json'),'externalFullTrackedBeforeSHA256':sha(r/'all-tracked-hashes-before.json'),'externalFullTrackedAfterPath':str(r/'all-tracked-hashes-after.json'),'externalFullTrackedAfterSHA256':sha(r/'all-tracked-hashes-after.json'),'productionTestArtBuildInputSourceCount':len(source_before),'onlySourceManifestChangedPath':target,'all207RuntimeResourcesExactB80':True,'runtime207ReferenceCommittedBuildSHA256':'3efed9961a04efbb051b3dc0785f8f15bda9e3c4e60834c3aca585e38260c9c0','nativeBundleFileCount':184,'nativeBundleManifestSHA256':sha(b/'bundle-manifest.json'),'native184CasesMethodsBudgetsPlansSealsAllExactB80':True,'allThreeWorkflowsExactB80':True,'nodeSyntaxCheckExitCode':0,'fullNpmTestBuildBrowserOrGpuRepeated':False,'oldActual900FerryFailureReclassifiedAsPass':False,'newRequired27Plus2ResultsClaimed':False,'gitStageCommitNetworkPerformed':False,'frozenWestOrRootSourceWritten':False}
save(q/'adoption-verification-receipt.json',receipt)
(q/'README.md').write_text('# Compact transit-scenario verification, 2026-10-05\n\nThis independent TEST child starts at exact West `b80eace6b3cf62eea3589c6dda40ed16251b480c`. It adopts only the sealed harbor-sample browser test projection. The original900-second Ferry trace had already alighted at the destination with riding false and the correct position, while a large full-state protocol return exhausted the verification window. That actual failed run and original raw trace remain failed historical evidence.\n\nOne local read-only snapshot projection retains position, simulation time, teleport revision, the complete transit state and interior buildingId, used at ten original callsites. Removing that helper and reversing those ten names reproduces the original executed8b/b80 test bytes exactly. Every original assertion, public input, physical route, photo, deadline, budget and other test stays intact. The sealed original CPU replay compares all consumed fields for13 actual original snapshots and preserves the actual post-E state; it grants no new browser or native success.\n\nAll207 production resources, the complete184-file native bundle and all workflows are byte-identical to b80. Only one tracked browser-test file changes; syntax check passes. Missing ignored59 city+13metropolis generated client chunks were populated with literal, SHA-verified b80 bytes in the new child without a build or tracked/vendor overwrite. The full396 source manifest is retained before/after, with only this browser-test SHA changed. No full npm, build, browser/GPU, staging, commit or network dispatch runs here. A new committed full12 functional gate must supply current actual27+2 browser outcomes.\n')
qfiles={str(p.relative_to(q)):{'bytes':p.stat().st_size,'sha256':sha(p)} for p in sorted(q.rglob('*')) if p.is_file()};save(q/'seal.json',{'status':'TEST_ONLY_COMPACT_TRANSIT_CPU_SYNTAX_EVIDENCE_SEALED_BROWSER_PENDING','fileCount':len(qfiles),'files':qfiles,'nativeOrBrowserPassClaimed':False})
paths=subprocess.check_output(['git','diff','--name-only','-z'],cwd=w).decode().split('\0')+subprocess.check_output(['git','ls-files','--others','--exclude-standard','-z'],cwd=w).decode().split('\0');stage=sorted(set(p for p in paths if p and p!='node_modules'))
assert not any(p.startswith(('src/','assets/','vendor/','dist/','tools/','.github/')) or '__pycache__' in p or p.endswith('.pyc') for p in stage)
(r/'exact-proposed-stage-file-list.txt').write_text('\n'.join(stage)+'\n');save(r/'exact-review-file-ledger.json',{'status':'UNSTAGED_ROOT_REVIEW_ONLY','fileCount':len(stage),'files':{p:{'bytes':(w/p).stat().st_size,'sha256':sha(w/p)} for p in stage}})
ready={'status':'READY_TEST_ONLY_NO_FURTHER_WRITES_UNTIL_ROOT_REVIEW','worktree':str(w),'parentCommit':head,'payloadTestSHA256':row['sha256'],'runtimeResources':207,'nativeBundleFiles':184,'allOtherTrackedFilesExactB80':True,'nodeCheckExitCode':0,'original13SnapshotCPUReceiptSHA256':sha(c/'CPU.stdout.json'),'adoptionVerificationReceiptSHA256':sha(q/'adoption-verification-receipt.json'),'qaSealSHA256':sha(q/'seal.json'),'qaFileCountExcludingSeal':len(qfiles),'exactProposedStageFileCount':len(stage),'exactProposedStageFileListPath':str(r/'exact-proposed-stage-file-list.txt'),'exactReviewFileLedgerPath':str(r/'exact-review-file-ledger.json'),'exactReviewFileLedgerSHA256':sha(r/'exact-review-file-ledger.json'),'fullNpmBuildGpuBrowserOrNetworkExecuted':False};save(r/'ready-for-root-review.json',ready);print(json.dumps(ready))
