"""Actual one-West runtime bridge, preserve native methods/budgets/history; requires final local actual checks."""
import ast,copy,hashlib,json,subprocess
from pathlib import Path
w=Path('/workspace/neon-candidates/harbor-mineral-pattern-correction-final-20261005');r=Path('/workspace/neon-candidates/harbor-mineral-pattern-correction-final-20261005-review');q=w/'docs/qa/mineral-pattern-correction-adoption-20261005';f=q/'final-production-checks';b=w/'tools/native-review';a=b/'runtime-amendments/mineral-pattern-correction-20261005';parent='9cf1c8613765addfb8592e0c4f9de14ce46210f9'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def load(p):return json.loads(p.read_text())
def save(p,v):assert not p.exists(),p;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
def cp(p,t):assert not t.exists(),t;t.parent.mkdir(parents=True,exist_ok=True);t.write_bytes(p.read_bytes())
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
assert subprocess.check_output(['git','rev-parse','HEAD'],cwd=w,text=True).strip()==parent
br=load(f/'build-receipt.json');tr=load(f/'full-npm-test-receipt.json');build=load(f/'build-info-original.json');assert br['exitCode']==tr['exitCode']==0 and tr['actualSummary']['pass']==tr['actualSummary']['tests']==381 and tr['actualSummary']['fail']==tr['actualSummary']['cancelled']==tr['actualSummary']['skipped']==0 and br['allSourceBeforeAfterEqual'] and tr['allSourceBeforeAfterEqual']
assert sha(f/'build-info-original.json')==br['buildInfoSHA256'] and build.get('revision') is None and len(build['assets'])==208
oldcatalog=load(r/'original-native199-bundle-manifest-9cf.json');oldexpect=load(r/'original-expected-runtime-dictionaries-9cf.json');oldwide=load(r/'original-frontage-wide-static-proof-9cf.json');oldbuild=load(r/'original-committed-9cf208-build-info.json');old=oldbuild['assets'];new=build['assets'];delta=br['exactRuntimeDeltaFrom9cf'];assert len(oldcatalog['files'])==199 and oldexpect['authored']['assets']==old
assert set(delta['changed'])=={'src/metropolis-western-ridge.js'} and not delta['added'] and not delta['removed'] and delta['unchangedCount']==207
for p,pin in new.items():assert sha(w/p)==sha(w/'dist'/p)==pin,p
sources=load(f/'all-production-test-source-hashes-after.json');assert len(sources)==401 and sources=={p:sha(w/p) for p in sources}
for p,row in oldcatalog['files'].items():assert sha(b/p)==row['sha256'],p
assert not a.exists();a.mkdir(parents=True)
for name in ['original-native199-bundle-manifest-9cf.json','original-expected-runtime-dictionaries-9cf.json','original-frontage-wide-static-proof-9cf.json','original-committed-9cf208-build-info.json']:cp(r/name,a/name)
cp(r/'pattern-correction-adoption-receipt.json',a/'actual-three-literal-payload-adoption-receipt.json');cp(q/'original-sealed-candidate/candidate-ledger.json',a/'original-producer-candidate-ledger.json');cp(q/'original-sealed-candidate/candidate-seal.json',a/'original-producer-candidate-seal.json')
rawrel='expected-build-provenance/authored-build-info-mineral-pattern-correction-20261005-'+br['buildInfoSHA256'][:12]+'.json';cp(f/'build-info-original.json',b/rawrel)
expected=copy.deepcopy(oldexpect);expected['authored']['assets']=new;expected['authored']['currentBuildInfo']={'path':rawrel,'sha256':sha(b/rawrel),'bytes':(b/rawrel).stat().st_size,'version':build['version'],'assetCount':len(new),'revision':None,'scope':'Actual one-West decorative pattern correction after final full381 rules once. Other207 resources are literal tested9cf. Original fishscale High picture remains rejected; no new pixel/native approval inferred.'};assert expected['baseline']==oldexpect['baseline'];write(b/'expected-runtime-dictionaries.json',expected)
producer=load(a/'original-producer-candidate-ledger.json');pins=['src/metropolis-western-ridge.js','src/harbor-district.js','src/harbor-frontage-profiles.js']
amend={'status':'ACTUAL_ONE_WEST_PATTERN_SOURCE_BRIDGE_NATIVE_ART_PENDING','parentCommit':parent,'actualBuildInfoPath':rawrel,'actualBuildInfoSHA256':sha(b/rawrel),'actualResourceCount':len(new),'exactRuntimeDeltaFrom9cf':delta,'sourceHashesBefore':{p:old[p] for p in pins},'sourceHashesAfter':{p:new[p] for p in pins},'actualPayloadAdoptionReceipt':{'path':'runtime-amendments/mineral-pattern-correction-20261005/actual-three-literal-payload-adoption-receipt.json','sha256':sha(a/'actual-three-literal-payload-adoption-receipt.json')},'originalProducerCPUProof':{'path':'docs/qa/mineral-pattern-correction-adoption-20261005/original-sealed-candidate/evidence/actual-cpu/actual-cpu-proof.json','sha256':producer['actualFullCityPhysicsProofSHA256'],'proofAuthoredByProducerNotIndependent':True,'reexecutedByAdopterOrSealer':False},'producerActualGeometryIdentity':producer['westCompleteGeometryIdentity'],'producerActualPhysicsIdentity':producer['fullPhysicsActualChecks'],'producerActualStandardProgrammeIdentity':producer['materialProgramIdentity'],'producerActualTextureDimensionsBudgetIdentity':producer['actualMapsUnchangedCountDimensionsFormatBudget'],'producerActualNorthAndLightOwnerIdentity':{'northIdentity':producer['northIdentity'],'ownership':producer['ownership']},'originalRejectedFishscaleHighImageReference':producer['originalDefectImageActuallyViewed'],'allOther207ResourcesIncludingLightingControlsTransportLiteral9cf':True,'allNativeExecutableMethodsInputsPlansSealsCasesAndBudgetsLiteral9cf':True,'baseline156EntireObjectUnchanged':True,'originalWideCasesPreparedHeadsAndHistoricalAmendmentsUnchanged':True,'all401SourceFrozenThroughActualFinal381AndBuild':True,'nativeArtAccepted':False,'pixelAcceptanceInheritedFrom9cf':False,'actualVRAMOrShaderCompileMeasuredBySealer':False,'scope':'Only West texel recipe, standardnormalScale.35 and nonperiodic macro colours change. Geometry position/normal/index/UV/AABB/sphere and standard shader programme/cache identity, map dimensions/caps and actual physics are producerCPU-backed. Explicit gameplay/control source identity permits source-scoped functional bridging only after actual outcomes; visual approval requires new actual High pixels.'}
save(a/'mineral-pattern-correction-source-amendment.json',amend)
wide=copy.deepcopy(oldwide);wide['sourceHashes']['authored'].update(amend['sourceHashesAfter']);wide['mineralPatternCorrectionGraphicsSourceAmendment']=amend
for k,v in oldwide.items():
 if k!='sourceHashes':assert wide[k]==v,k
write(b/'methods/harbor/evidence/frontage-wide-static-proof.json',wide)
p=b/'README.md';p.write_text(p.read_text()+'\nCurrent West pattern correction is actual null build '+br['buildInfoSHA256'][:12]+' with208 resources after381 final rules; only src/metropolis-western-ridge.js differs from9cf, other207 resources literal. Original fishscale High image remains rejected. Standardprogramme/geometry/UV/mapdimensions/caps and gameplay physics bridges retain original producerCPU scope, not an independent or native proof. All native methods/inputs/budgets including transport e449 remain literal9cf. New-source High pixels still require actual review.\n')
files={str(p.relative_to(b)):{'bytes':p.stat().st_size,'sha256':sha(p)} for p in sorted(b.rglob('*')) if p.is_file() and p!=b/'bundle-manifest.json'};assert not any(p.is_symlink() or '__pycache__' in p.parts or p.suffix=='.pyc' for p in b.rglob('*'))
receipt={'status':'ACTUAL_ONE_WEST_PATTERN_METADATA_PREPARED_NATIVE_ART_PENDING','parentCommit':parent,'parentNative199ManifestSHA256':sha(a/'original-native199-bundle-manifest-9cf.json'),'parentRuntimeAssets':old,'actualRuntimeAssets':new,'exactRuntimeDeltaFrom9cf':delta,'actualBuildInfoSHA256':sha(b/rawrel),'actualRawBuildInfoPath':rawrel,'actualResourceCount':len(new),'expectedNativeBundleFileCount':len(files),'expectedNativeBundleFiles':files,'baseline156EntireObjectUnchanged':True,'allNativeFunctionalBytesLiteral9cf':True,'nativeArtAccepted':False};save(r/'metadata-refresh-receipt.json',receipt)
src=Path('/workspace/neon-candidates/harbor-material-lighting-final-20261005-review/strict-final-idle-material-lighting-transport-source-pin-sealer.py');assert sha(src)=='ec91bbb5113a13e2fe638ea183c36ea6bafc360541c1e2155c1af8577c19adca';cp(src,q/'original-199-strict-source-pin-sealer.py');script=src.read_text();start=script.index(' # Strict actual combined bridge:');end=script.index(" problem(build['assets']==authored['assets']",start)
guard=f''' # Strict actual single-West bridge; no arbitrary counts or unchanged executable method rewrites.
 final_receipt_path=Path({str(r/'metadata-refresh-receipt.json')!r})
 problem(digest(final_receipt_path)=={sha(r/'metadata-refresh-receipt.json')!r},'Actual West-only metadata receipt changed')
 final_receipt=load(final_receipt_path)
 problem(final_receipt.get('status')=='ACTUAL_ONE_WEST_PATTERN_METADATA_PREPARED_NATIVE_ART_PENDING','Actual West-only source receipt missing')
 problem(digest(info_path)=={br['buildInfoSHA256']!r},'Actual final pattern nullbuild changed')
 problem(build.get('revision') is None and len(build['assets'])==len(authored['assets'])==208,'Actual pattern208/nullrevision differs')
 parent_path=b/'runtime-amendments/mineral-pattern-correction-20261005/original-committed-9cf208-build-info.json'
 problem(digest(parent_path)=='b7fff54990d24db3441124ee822d188b12531f3336667aa896e070e5beaade88','Original committed9cf raw208 changed')
 parent_assets=load(parent_path)['assets'];problem(parent_assets==final_receipt['parentRuntimeAssets'],'Entire original9cf dictionary changed')
 delta={{'added':{{p:build['assets'][p] for p in sorted(build['assets'].keys()-parent_assets.keys())}},'changed':{{p:{{'before':parent_assets[p],'after':build['assets'][p]}} for p in sorted(build['assets'].keys()&parent_assets.keys()) if build['assets'][p]!=parent_assets[p]}},'removed':sorted(parent_assets.keys()-build['assets'].keys()),'unchangedCount':sum(build['assets'][p]==parent_assets[p] for p in build['assets'].keys()&parent_assets.keys())}}
 problem(delta==final_receipt['exactRuntimeDeltaFrom9cf'] and set(delta['changed'])=={{'src/metropolis-western-ridge.js'}} and not delta['added'] and not delta['removed'] and delta['unchangedCount']==207,'Pattern bridge exceeds single-West decorative change')
 problem(build['assets']==final_receipt['actualRuntimeAssets'],'Entire actual208 dictionary changed')
 for rel,pin in final_receipt['actualRuntimeAssets'].items():
  problem(digest(contained(w,rel))==pin,'Actual pattern source/asset changed:'+rel)
  problem(digest(contained(w/'dist',rel))==pin,'Actual pattern dist resource changed:'+rel)
 actual_native_map={{str(p.relative_to(b)):{{'bytes':p.stat().st_size,'sha256':digest(p)}} for p in b.rglob('*') if p.is_file() and p!=b/'bundle-manifest.json'}}
 problem(len(actual_native_map)==final_receipt['expectedNativeBundleFileCount']=={len(files)} and actual_native_map==final_receipt['expectedNativeBundleFiles'],'Full strict pattern native inventory changed')
 problem(not any(p.is_symlink() or '__pycache__' in p.parts or p.suffix=='.pyc' for p in b.rglob('*')),'Bundle cannot admit cache/symlink')
 original_expected=load(b/'runtime-amendments/mineral-pattern-correction-20261005/original-expected-runtime-dictionaries-9cf.json');problem(original_expected['baseline']==baseline and len(baseline['assets'])==156,'Baseline156 entire object changed')
 original_catalog=load(b/'runtime-amendments/mineral-pattern-correction-20261005/original-native199-bundle-manifest-9cf.json');problem(digest(b/'runtime-amendments/mineral-pattern-correction-20261005/original-native199-bundle-manifest-9cf.json')==final_receipt['parentNative199ManifestSHA256'],'Original native199 catalog changed')
 permitted_changes={{'README.md','expected-runtime-dictionaries.json','methods/harbor/evidence/frontage-wide-static-proof.json'}}
 for rel,pin in original_catalog['files'].items():
  if rel not in permitted_changes:problem(digest(contained(b,rel))==pin['sha256'],'Unapproved original executable/input/plan/seal/case/budget changed:'+rel)
 original_wide=load(b/'runtime-amendments/mineral-pattern-correction-20261005/original-frontage-wide-static-proof-9cf.json');current_wide=load(b/'methods/harbor/evidence/frontage-wide-static-proof.json')
 for key,value in original_wide.items():
  if key!='sourceHashes':problem(current_wide.get(key)==value,'Original B physical cases/preparedheads/history changed:'+key)
 notes.append('One-West decorative source bridge only, other207 actual resources and all native executable methods/inputs/budgets exact9cf; producerCPU proofs retained, no native/pixel acceptance inherited.')
'''
script=script[:start]+guard+script[end:]
line=next(x for x in script.splitlines() if 'active_b_amendment=wide.get(' in x);script=script.replace(line,line.replace('active_b_amendment=','active_b_amendment=wide.get(\'mineralPatternCorrectionGraphicsSourceAmendment\',')+')')
line=next(x for x in script.splitlines() if x.startswith(" catalog['materialNightLightingRuntimeAmendment']="));script=script.replace(line," problem(catalog['materialNightLightingRuntimeAmendment']==original_catalog['materialNightLightingRuntimeAmendment'],'Historical material/night/transport amendment changed')")
insert=" catalog['mineralPatternCorrectionRuntimeAmendment']={'status':'ACTUAL_ONE_WEST_DECORATIVE_SOURCE_BRIDGE_NATIVE_PIXEL_PENDING','parentNativeBundleFileCount':199,'parentNativeBundleManifestSHA256':final_receipt['parentNative199ManifestSHA256'],'actualBuildInfoSHA256':info['sha256'],'actualResourceCount':len(authored['assets']),'exactRuntimeDeltaFrom9cf':final_receipt['exactRuntimeDeltaFrom9cf'],'currentExactNativeBundleFileCount':final_receipt['expectedNativeBundleFileCount'],'sourceAmendmentPath':'runtime-amendments/mineral-pattern-correction-20261005/mineral-pattern-correction-source-amendment.json','allNativeExecutableMethodsInputsPlansSealsCasesAndBudgetsUnchanged':True,'old9cfArtRejectionAndFailuresPreserved':True,'producerCPUReexecutedBySealer':False,'nativeArtAccepted':False}\n"
script=script.replace(" catalog['activityPinRefresh']=",insert+" catalog['activityPinRefresh']=",1);ast.parse(script);dst=r/'strict-one-west-pattern-source-pin-sealer.py';assert not dst.exists();dst.write_text(script)
save(r/'sealer-derivation-receipt.json',{'status':'NEW_STRICT_ONE_WEST_COPY_FROM_IMMUTABLE199_SEALER','originalSHA256':sha(src),'newSealerSHA256':sha(dst),'actualRawBuildInfoSHA256':br['buildInfoSHA256'],'actualResourceCount':len(new),'exactRuntimeDelta':delta,'expectedNativeBundleFileCount':len(files),'oldFiveChangeGuardCompletelyReplacedNotBlindlyPreserved':True,'nativeMethodsExecutedBySealer':False})
print(json.dumps({'status':'ONE_WEST_METADATA_PREPARED','actualResourceCount':len(new),'actualNativeBundleFileCount':len(files),'metadataReceiptSHA256':sha(r/'metadata-refresh-receipt.json'),'strictSealerSHA256':sha(dst),'expectedRuntimeDictionariesSHA256':sha(b/'expected-runtime-dictionaries.json')}))
